# Generated by Django 4.1.5 on 2023-04-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complain_Music', to='Music.music')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complain_Poster', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Music', to='Music.music')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Poster', to='User.user')),
            ],
        ),
    ]
