# Generated by Django 4.1.5 on 2023-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(verbose_name='评论音乐id')),
                ('poster_id', models.IntegerField(default=-1, verbose_name='评论发布者id')),
                ('content', models.TextField()),
                ('type', models.IntegerField(verbose_name='评论种类')),
                ('likes', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(default=-1, verbose_name='投诉对象id')),
                ('poster_id', models.IntegerField(default=-1, verbose_name='投诉发表者id')),
                ('content', models.TextField()),
                ('type', models.IntegerField(verbose_name='评论种类')),
                ('state', models.IntegerField(verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('receiver_id', models.IntegerField(default=0, verbose_name='收到私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.IntegerField(verbose_name='读状态')),
            ],
        ),
        migrations.CreateModel(
            name='MusicListToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicListToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='PostToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('message_id', models.IntegerField(default=0, verbose_name='消息')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(verbose_name='验证码内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
    ]
