# Generated by Django 4.2.1 on 2023-05-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(verbose_name='评论音乐id')),
                ('poster_id', models.IntegerField(default=-1, verbose_name='评论发布者id')),
                ('content', models.TextField()),
                ('type', models.IntegerField(verbose_name='评论种类')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(default=-1, verbose_name='投诉对象id')),
                ('poster_id', models.IntegerField(default=-1, verbose_name='投诉发表者id')),
                ('content', models.TextField()),
                ('type', models.IntegerField(verbose_name='评论种类')),
                ('state', models.IntegerField(verbose_name='审核状态')),
                ('audit_time', models.DateTimeField(blank=True)),
                ('result', models.IntegerField(blank=True, verbose_name='审核结果')),
                ('reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='点赞用户id')),
                ('object_id', models.IntegerField(verbose_name='点赞对象id')),
                ('type', models.IntegerField(verbose_name='点赞对象种类')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('receiver_id', models.IntegerField(default=0, verbose_name='收到私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(blank=True, verbose_name='消息对应的对象id')),
                ('type', models.IntegerField(blank=True, verbose_name='消息对应的对象种类')),
                ('message_type', models.IntegerField(verbose_name='消息种类')),
                ('state', models.IntegerField(default=0, verbose_name='读状态')),
            ],
        ),
        migrations.CreateModel(
            name='MusicListToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicListToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('type', models.IntegerField(verbose_name='分享对象的种类')),
                ('object_id', models.IntegerField(verbose_name='分享对象的id')),
            ],
        ),
        migrations.CreateModel(
            name='PostToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('replyer_id', models.IntegerField(verbose_name='回复者id')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('root_id', models.IntegerField(verbose_name='根评论id')),
                ('fa_id', models.IntegerField(verbose_name='父评论id')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('isLevel2', models.IntegerField(verbose_name='是否为二级评论（一级回复）')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('message_id', models.IntegerField(default=0, verbose_name='消息')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(verbose_name='验证码内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
    ]