# Generated by Django 3.2.18 on 2023-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='', max_length=114, verbose_name='审核任务id')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐id')),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
