# Generated by Django 4.1.5 on 2023-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('receiver_id', models.IntegerField(default=0, verbose_name='收到私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='music',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='music',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='poster',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='music_id',
            field=models.IntegerField(default=-1, verbose_name='评论音乐id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='poster_id',
            field=models.IntegerField(default=-1, verbose_name='评论发布者id'),
        ),
        migrations.AddField(
            model_name='complain',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='music_id',
            field=models.IntegerField(default=-1, verbose_name='投诉音乐id'),
        ),
        migrations.AddField(
            model_name='complain',
            name='poster_id',
            field=models.IntegerField(default=-1, verbose_name='投诉发表者id'),
        ),
    ]
