# Generated by Django 4.1.5 on 2023-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='', max_length=114, verbose_name='审核任务id')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐id')),
            ],
        ),
    ]
