# Generated by Django 4.2.1 on 2023-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_object_id',
            field=models.IntegerField(default=-1, verbose_name='来源id'),
            preserve_default=False,
        ),
    ]
