# Generated by Django 4.1.5 on 2023-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_message_musictocomment_musictocomplain_usertocomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicListToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='MusicListToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiclist_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('complain_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('poster_id', models.IntegerField(default=0, verbose_name='发送私信者的id')),
                ('content', models.TextField(verbose_name='私信内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='PostToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0, verbose_name='音乐主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户 主体')),
                ('message_id', models.IntegerField(default=0, verbose_name='消息')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(verbose_name='验证码内容')),
                ('cre_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='music_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.IntegerField(default=0, verbose_name='评论音乐id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.IntegerField(default=0, verbose_name='评论种类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='object_id',
            field=models.IntegerField(default=-1, verbose_name='投诉对象id'),
        ),
        migrations.AddField(
            model_name='complain',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='type',
            field=models.IntegerField(default=0, verbose_name='评论种类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.IntegerField(default=0, verbose_name='读状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=0, max_length=32, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
