# Generated by Django 4.1.5 on 2023-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_jobtomusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
