# Generated by Django 4.1.5 on 2023-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0005_alter_likes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_object_id',
            field=models.IntegerField(default=-1, verbose_name='来源id'),
            preserve_default=False,
        ),
    ]
