# Generated by Django 4.1.5 on 2023-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('follow_num', models.IntegerField(default=0)),
                ('fan_num', models.IntegerField(default=0)),
                ('like_list', models.IntegerField(verbose_name='个人喜爱歌单id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserListenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户')),
                ('music_id', models.IntegerField(default=0, verbose_name='音乐')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户')),
                ('comment_id', models.IntegerField(default=0, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='UserToComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户')),
                ('complain_id', models.IntegerField(default=0, verbose_name='投诉')),
            ],
        ),
        migrations.CreateModel(
            name='UserToFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('fan_id', models.IntegerField(default=0, verbose_name='粉丝')),
            ],
        ),
        migrations.CreateModel(
            name='UserToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('follow_id', models.IntegerField(default=0, verbose_name='关注的用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserToMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户')),
                ('music_list_id', models.IntegerField(default=0, verbose_name='歌单')),
            ],
        ),
    ]
