# Generated by Django 4.1.5 on 2023-05-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_time',
            new_name='created_date',
        ),
    ]
