# Generated by Django 3.2.18 on 2023-05-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(default='暂无介绍', max_length=150)),
                ('cover_path', models.CharField(default='', max_length=100)),
                ('album_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToLikeMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户')),
                ('music_list_id', models.IntegerField(default=0, verbose_name='喜爱歌单')),
            ],
        ),
        migrations.CreateModel(
            name='UserToSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('singer_id', models.IntegerField(default=0, verbose_name='喜爱歌手')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activity_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='暂无介绍', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='暂无', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='max_record',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userlistenhistory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userlistenhistory',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usertomusiclist',
            name='music_list_id',
            field=models.IntegerField(default=0, verbose_name='创建歌单'),
        ),
    ]
