# Generated by Django 4.1.5 on 2023-05-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_created_time_user_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
