# Generated by Django 4.1.5 on 2023-04-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('file_loc', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('listen_time', models.IntegerField()),
                ('music_front', models.ImageField(upload_to='')),
                ('music_name', models.CharField(max_length=100)),
                ('words', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music_Creator', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('music_list_front', models.ImageField(upload_to='')),
                ('music_list_profile', models.TextField()),
                ('views', models.IntegerField()),
                ('music_num', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MusicList_Creator', to='User.user')),
                ('music', models.ManyToManyField(to='Music.music')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('label_music', models.ManyToManyField(to='Music.music')),
                ('label_music_list', models.ManyToManyField(to='Music.musiclist')),
            ],
        ),
    ]
