# Generated by Django 4.1.5 on 2023-06-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('music_path', models.CharField(default='', max_length=100)),
                ('cover_path', models.CharField(default='https://hypermusic-1317300880.cos.ap-beijing.myqcloud.com/Default_Music_Cover.png', max_length=100)),
                ('lyrics_path', models.CharField(default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('listen_nums', models.IntegerField(default=0)),
                ('is_original', models.BooleanField(default=False)),
                ('description', models.TextField(default='这首歌还没有介绍哦')),
                ('is_audit', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music_Uploader', to='User.user')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music_Singer', to='User.singer')),
            ],
        ),
        migrations.CreateModel(
            name='SingerToMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField(default=0, verbose_name='歌手')),
                ('music_id', models.IntegerField(default=0, verbose_name='歌曲')),
            ],
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('music_num', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_path', models.CharField(default='https://hypermusic-1317300880.cos.ap-beijing.myqcloud.com/Default_Music_Cover.png', max_length=100)),
                ('description', models.TextField(default='此歌单还没有介绍哦', max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MusicList_Creator', to='User.user')),
                ('music', models.ManyToManyField(to='Music.music')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('label_music', models.ManyToManyField(to='Music.music')),
                ('label_music_list', models.ManyToManyField(to='Music.musiclist')),
                ('label_singer', models.ManyToManyField(to='User.singer')),
            ],
        ),
    ]
