<<<<<<< HEAD
# Generated by Django 3.2.18 on 2023-05-25 03:22
=======
# Generated by Django 4.1.5 on 2023-05-24 13:15
>>>>>>> origin/dev1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='create_time',
            new_name='create_date',
        ),
    ]
