# Generated by Django 3.2.18 on 2023-05-21 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20230521_1252'),
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerToAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField(default=0, verbose_name='歌手')),
                ('album_id', models.IntegerField(default=0, verbose_name='专辑')),
            ],
        ),
        migrations.CreateModel(
            name='SingerToMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField(default=0, verbose_name='歌手')),
                ('music_id', models.IntegerField(default=0, verbose_name='歌曲')),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='music',
            name='file_loc',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_front',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='music_list_front',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='music_list_profile',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='views',
        ),
        migrations.AddField(
            model_name='label',
            name='label_singer',
            field=models.ManyToManyField(to='User.Singer'),
        ),
        migrations.AddField(
            model_name='music',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 21, 4, 52, 15, 944062, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='front_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='music',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='music_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Music_Creator', to='User.singer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiclist',
            name='description',
            field=models.TextField(default='暂无介绍', max_length=200),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='front_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='listen_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musiclist',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiclist',
            name='type',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music_Uploader', to='User.user'),
        ),
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='listen_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='words',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('music_num', models.IntegerField(default=0)),
                ('cover_path', models.CharField(default='', max_length=100)),
                ('publish_date', models.DateField()),
                ('introduction', models.TextField(default='暂无介绍', max_length=200)),
                ('music', models.ManyToManyField(to='Music.Music')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Singer', to='User.singer')),
            ],
        ),
    ]
