# Generated by Django 4.1.5 on 2023-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_rename_create_time_music_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_audit',
            field=models.BooleanField(default=False),
        ),
    ]
