# Generated by Django 4.1.5 on 2023-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_music_is_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_path',
            field=models.CharField(default='https://hypermusic-1317300880.cos.ap-beijing.myqcloud.com/Default_Music_Cover.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='cover_path',
            field=models.CharField(default='https://hypermusic-1317300880.cos.ap-beijing.myqcloud.com/Default_Music_Cover.png', max_length=100),
        ),
    ]
